# Generated by Django 3.2.6 on 2021-08-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='http://google.com'),
            preserve_default=False,
        ),
    ]
